const Data=[
    {
        "ID":1,
        "name":"rajesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":2,
        "name":"Sachin",
        "email":"raj123@gmail.com"
    },
    {
        "ID":3,
        "name":"manoj",
        "email":"raj123@gmail.com"
    },
    {
        "ID":4,
        "name":"sanjay",
        "email":"raj123@gmail.com"
    },
    {
        "ID":5,
        "name":"praveen",
        "email":"raj123@gmail.com"
    },
    {
        "ID":6,
        "name":"rohan",
        "email":"raj123@gmail.com"
    },
    {
        "ID":7,
        "name":"vikas",
        "email":"raj123@gmail.com"
    },
    {
        "ID":8,
        "name":"rupesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":9,
        "name":"deepesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":10,
        "name":"ranu",
        "email":"raj123@gmail.com"
    },
    {
        "ID":11,
        "name":"salini",
        "email":"raj123@gmail.com"
    },
    {
        "ID":12,
        "name":"rajesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":13,
        "name":"rohitrajesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":14,
        "name":"rajesh",
        "email":"raj123@gmail.com"
    },
    {
        "ID":15,
        "name":"manju",
        "email":"raj123@gmail.com"
    }
]

export default Data;